More detailed reporting (in 'build.status' and 'run.status') while building and running tests.

diff --git a/src/tests/build b/src/tests/build
--- a/src/tests/build
+++ b/src/tests/build
@@ -25,18 +25,28 @@ cd "$(dirname "$0")" || exit -1
 failed_list=$(mktemp)
 succeeded_list=$(mktemp)
 
+number_of_builds=$(find ./ -mindepth 2 -type f -name \*.gpr | wc -l)
+build_number=0
+
 echo -n "Building tests...  "
 
 for file in $(find ./ -mindepth 2 -type f -name \*.gpr | sort); do
-   test=$(echo ${file} | cut -d/ -f2)
+   let build_number++
+
+   echo ${build_number}/${number_of_builds}$'\tBuilding '${file}'...' 1>&2
 
    if gnatmake -P ${file} 1>${file}.output \
                           2>${file}.errors; then
-      echo ${test} >> ${succeeded_list}
+      echo ${build_number}/${number_of_builds}$'\tBuild succeeded' 1>&2
+
+      echo ${file} >> ${succeeded_list}
    else
-      echo ${test} >>    ${failed_list}
+      echo ${build_number}/${number_of_builds}$'\tBuild failed' 1>&2
+
+      echo ${file} >>    ${failed_list}
    fi
-done
+done \
+  2>build.status
 
 total=$(cat ${succeeded_list} ${failed_list} | wc -l)
 failed=$(cat ${failed_list} | wc -l)
diff --git a/src/tests/run b/src/tests/run
--- a/src/tests/run
+++ b/src/tests/run
@@ -27,9 +27,14 @@ cd "$(dirname "$0")" || exit -1
 failed_list=$(mktemp)
 succeeded_list=$(mktemp)
 
+number_of_runs=$(find ./ -mindepth 2 -type f -perm +100 | wc -l)
+run_number=0
+
 echo -n "Running tests...   "
 
 for file in $(find ./ -mindepth 2 -type f -perm +100 | sort); do
+   let run_number++
+
    if [ ! -f ${file}.arguments ]; then
       touch ${file}.arguments
    fi
@@ -40,6 +45,8 @@ for file in $(find ./ -mindepth 2 -type f -perm +100 | sort); do
       allowed_time_in_seconds=${default_allowed_time_in_seconds}
    fi
 
+   echo ${run_number}/${number_of_runs}$'\tRunning '${file}' for at most '${allowed_time_in_seconds}' seconds...' 1>&2
+
    ./${file} $(cat ${file}.arguments) 1>${file}.output \
                                       2>${file}.errors \
                                       &
@@ -47,20 +54,31 @@ for file in $(find ./ -mindepth 2 -type f -perm +100 | sort); do
 
    (
      sleep ${allowed_time_in_seconds}
-     kill ${pid} 2>/dev/null
-     sleep 1
-     kill -9 ${pid} 2>/dev/null
+     if [ -d /proc/${pid} ]; then
+        echo ${run_number}/${number_of_runs}$'\tTerminating '${file}'...' 1>&2
+        kill ${pid} 2>/dev/null
+        sleep 1
+        if [ -d /proc/${pid} ]; then
+           echo ${run_number}/${number_of_runs}$'\tKilling '${file}'...' 1>&2
+           kill -9 ${pid} 2>/dev/null
+        fi
+     fi
    ) &
 
    wait ${pid}
    result=$?
 
    if [ ${result} -eq 0 ]; then
+      echo ${run_number}/${number_of_runs}$'\tRun succeeded.' 1>&2
+
       echo "${file}"             >> ${succeeded_list}
    else
+      echo ${run_number}/${number_of_runs}$'\tRun failed with exit code '${result}'.' 1>&2
+
       echo "${file} (${result})" >>    ${failed_list}
    fi
-done 2>/dev/null
+done \
+  2>run.status
 
 total=$(cat ${succeeded_list} ${failed_list} | wc -l)
 failed=$(cat ${failed_list} | wc -l)
