Report exception terminated test cases explicitly.

diff --git a/src/tests/run b/src/tests/run
--- a/src/tests/run
+++ b/src/tests/run
@@ -73,6 +73,10 @@ for file in $(find ./ -mindepth 2 -type f -perm +100 | sort); do
       echo ${run_number}/${number_of_runs}$'\tRun succeeded.' 1>&2
 
       echo "${file}"             >> ${succeeded_list}
+   elif [ ${result} -eq 123 ]; then
+      echo ${run_number}/${number_of_runs}$'\tRun was terminated by an exception.' 1>&2
+
+      echo "${file} (exception)" >>    ${failed_list}
    elif [ ${result} -eq 137 ]; then
       echo ${run_number}/${number_of_runs}$'\tRun was terminated by SIGKILL.' 1>&2
 
